name: Continue Config
version: 1.0.0
models:
  - name: granite
    provider: openai
    apiBase: https://granite-4-tiny-demo.apps.cluster-nlx4n.nlx4n.sandbox5538.opentlc.com/v1/
    model: granite-4-tiny
    apiKey:
    roles:
      - chat
      - edit
      - apply
      - autocomplete
      - summarize
    capabilities:
      - tool_use
  - name: gpt-oss
    provider: openai
    apiBase: https://openrouter.ai/api/v1
    model: openai/gpt-oss-20b
    apiKey: 
    roles:
      - chat
      - edit
      - apply
      - autocomplete
      - summarize
    capabilities:
      - tool_use
context:
  - uses: continuedev/code-context
    with: {}
  - uses: continuedev/docs-context
    with: {}
  - uses: continuedev/diff-context
    with: {}
  - uses: continuedev/terminal-context
    with: {}
  - uses: continuedev/problems-context
    with: {}
  - uses: continuedev/folder-context
    with: {}
  - uses: continuedev/codebase-context
    with: {}