---
apiVersion: v1
data:
  app-config.json: |
    {
      "app": {
        "name": "GraphRAG LanceDB",
        "version": "1.0.0",
        "environment": "production"
      },
      "server": {
        "port": 3000,
        "cors": {
          "enabled": true,
          "origins": ["*"]
        },
        "rateLimit": {
          "enabled": true,
          "windowMs": 900000,
          "max": 100
        }
      },
      "swagger": {
        "enabled": true,
        "path": "/api-docs"
      },
      "logging": {
        "level": "info",
        "format": "combined"
      }
    }
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: llama-stack-mcp
    app.kubernetes.io/name: graphrag-db
    app.kubernetes.io/part-of: hr-enterprise
    app.kubernetes.io/version: 1.0.0
  name: graphrag-db
  namespace: llama-stack-mcp-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: llama-stack-mcp
    app.kubernetes.io/name: graphrag-db
    app.kubernetes.io/part-of: graphrag-db
  name: graphrag-db
  namespace: llama-stack-mcp-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: llama-stack-mcp
      app.kubernetes.io/name: graphrag-db
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: llama-stack-mcp
        app.kubernetes.io/name: graphrag-db
    spec:
      containers:
      - env:
        - name: ENABLE_RATE_LIMITING
          value: "true"
        - name: ENABLE_SWAGGER
          value: "true"
        - name: NODE_ENV
          value: production
        - name: PORT
          value: "3000"
        - name: CONFIG_MAP_NAME
          value: llama-stack-mcp-graphrag-db-config
        image: quay.io/oawofolurh/coldfusion-graphrag:0.0.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: graphrag-db
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: false
          runAsNonRoot: true
